//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuvarBlog.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanicilar()
        {
            this.Makalelers = new HashSet<Makaleler>();
            this.Yorumlars = new HashSet<Yorumlar>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage ="Kullanýcý adý boþ geçilemez.")]
        public string KullaniciAdi { get; set; }
        [Required(ErrorMessage = "Þifre boþ geçilemez.")]
        public string Sifre { get; set; }
        [Required(ErrorMessage = "Ad Soyad boþ geçilemez.")]
        public string Adsoyad { get; set; }
        public Nullable<int> YetkiID { get; set; }
        public string Foto { get; set; }
        [Required(ErrorMessage = "Mail adresi boþ geçilemez.")]
        public string Mail { get; set; }
    
        public virtual Yetkiler Yetkiler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Makaleler> Makalelers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorumlar> Yorumlars { get; set; }
    }
}
